# Auto-generated by scripts/generate_stubs.py — do not edit manually
# Source: scpv2/resources/data/keypair.json
from __future__ import annotations

class KeypairResource:
    def list(self, limit: str | None = None, marker: str | None = None) -> dict: ...
    def create(self, name: str | None = None, public_key: str | None = None, tags: list | None = None) -> dict: ...
