# Auto-generated by scripts/generate_stubs.py — do not edit manually
# Source: scpv2/resources/data/keypair.json
from __future__ import annotations
from typing import Literal, overload

class KeypairClient:
    def list_keypairs(self, limit: str | None = None, marker: str | None = None) -> dict: ...
    def create_keypair(self, name: str, public_key: str | None = None, tags: list | None = None) -> dict: ...
