# Auto-generated by scripts/generate_stubs.py — do not edit manually
from __future__ import annotations
from typing import Iterator

class PageIterator:
    def __iter__(self) -> Iterator[dict]: ...
    def build_full_result(self) -> dict: ...

class Paginator:
    def paginate(self, **kwargs: object) -> PageIterator: ...
