# Auto-generated by scripts/generate_stubs.py — do not edit manually
from typing import Literal

class RetryConfig:
    max_attempts: int
    mode: str
    def __init__(
        self,
        max_attempts: int = 3,
        mode: Literal["standard", "legacy"] = "standard",
    ) -> None: ...

class RetryHandler:
    config: RetryConfig
    def __init__(self, config: RetryConfig | None = None) -> None: ...
    def is_retryable(self, status_code: int) -> bool: ...
    def backoff(self, attempt: int) -> None: ...
