# Auto-generated by scripts/generate_stubs.py — do not edit manually
# Source: scpv2/resources/data/subnet.json
from __future__ import annotations
from typing import Literal, overload

class SubnetClient:
    def create_subnet(self, name: str, cidr: str, type: str, vpc_id: str, description: str | None = None, gateway_ip_address: str | None = None, allocation_pools: str | None = None, dns_nameservers: str | None = None, host_routes: str | None = None, tags: list | None = None) -> dict: ...
