# Auto-generated by scripts/generate_stubs.py — do not edit manually
# Source: scpv2/resources/data/subnet.json
from __future__ import annotations

class SubnetResource:
    def create(self, name: str | None = None, cidr: str | None = None, type: str | None = None, vpc_id: str | None = None, description: str | None = None, gateway_ip_address: str | None = None, allocation_pools: str | None = None, dns_nameservers: str | None = None, host_routes: str | None = None, tags: list | None = None) -> dict: ...
