# Auto-generated by scripts/generate_stubs.py — do not edit manually
# Source: scpv2/resources/data/subnet.json
from __future__ import annotations
from scpv2.stubs.collection import Collection

class SubnetResource:
    subnets: Collection
    def list(self, size: int | None = None, page: int | None = None, sort: str | None = None, id: str | None = None, name: str | None = None, type: str | None = None, cidr: str | None = None, state: str | None = None, vpc_id: str | None = None, vpc_name: str | None = None) -> dict: ...
    def create(self, name: str | None = None, cidr: str | None = None, type: str | None = None, vpc_id: str | None = None, description: str | None = None, gateway_ip_address: str | None = None, allocation_pools: str | None = None, dns_nameservers: str | None = None, host_routes: str | None = None, tags: list | None = None) -> dict: ...
