# Auto-generated by scripts/generate_stubs.py — do not edit manually
# Source: scpv2/resources/data/vpc.json
from __future__ import annotations
from scpv2.stubs.collection import Collection

class VpcResource:
    vpcs: Collection
    def list(self, size: int | None = None, page: int | None = None, sort: str | None = None, id: str | None = None, name: str | None = None, state: str | None = None, cidr: str | None = None) -> dict: ...
    def create(self, name: str | None = None, cidr: str | None = None, description: str | None = None, tags: list | None = None) -> dict: ...
    def delete(self, vpc_id: str | None = None) -> dict: ...
