# Auto-generated by scripts/generate_stubs.py — do not edit manually
from __future__ import annotations
from typing import Literal, overload

from scpv2.stubs.ec2_client import Ec2Client
from scpv2.stubs.s3_client import S3Client
from scpv2.stubs.subnet_client import SubnetClient
from scpv2.stubs.virtualserver_client import VirtualserverClient
from scpv2.stubs.vpc_client import VpcClient

class Session:
    @overload
    def client(self, service_name: Literal["ec2"]) -> Ec2Client: ...
    @overload
    def client(self, service_name: Literal["s3"]) -> S3Client: ...
    @overload
    def client(self, service_name: Literal["subnet"]) -> SubnetClient: ...
    @overload
    def client(self, service_name: Literal["virtualserver"]) -> VirtualserverClient: ...
    @overload
    def client(self, service_name: Literal["vpc"]) -> VpcClient: ...
    def client(self, service_name: str) -> object: ...
