#!/usr/bin/env python3
"""
scripts/generate_stubs.py
scpv2/resources/data/*.json 을 읽어서 scpv2/stubs/ 디렉토리에 .pyi stub 파일을 자동 생성합니다.

사용법:
    python scripts/generate_stubs.py

생성 결과:
    scpv2/stubs/collection.pyi         : Collection 클래스 타입 정의
    scpv2/stubs/{service}_client.pyi   : 서비스별 Client 클래스 타입 정의
    scpv2/stubs/{service}_resource.pyi : 서비스별 ServiceResource 클래스 타입 정의
    scpv2/session.pyi                  : Session.client() / Session.resource() overload 타입 정의
"""

import json
import os

_ROOT             = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR          = os.path.join(_ROOT, "scpv2", "resources", "data")
OUT_DIR           = os.path.join(_ROOT, "scpv2", "stubs")
SESSION_STUB_DIR  = os.path.join(_ROOT, "scpv2")

PARAM_TYPE_MAP = {
    "size":       "int",
    "page":       "int",
    "page_count": "int",
    "count":      "int",
    "max_count":  "int",
    "lock":       "bool",
    "tags":       "list",
    "networks":   "list",
    "volumes":    "list",
    "security_groups": "list",
    "metadata":   "dict",
}


def _py_type(param_name: str) -> str:
    return PARAM_TYPE_MAP.get(param_name, "str")


def _param_sig(name: str, required: list) -> str:
    t = _py_type(name)
    if name in required:
        return f"{name}: {t}"
    return f"{name}: {t} | None = None"


def _client_class_name(service_name: str) -> str:
    return f"{service_name.capitalize()}Client"


def _resource_class_name(service_name: str) -> str:
    return f"{service_name.capitalize()}Resource"


def _client_module_name(service_name: str) -> str:
    return f"{service_name}_client"


def _resource_module_name(service_name: str) -> str:
    return f"{service_name}_resource"


# ── Collection stub ──────────────────────────────────────────────────────────

def _generate_collection_stub() -> str:
    return """\
# Auto-generated by scripts/generate_stubs.py — do not edit manually
from __future__ import annotations
from typing import Iterator

class Collection:
    def __iter__(self) -> Iterator[dict]: ...
    def all(self) -> Collection: ...
    def filter(self, **kwargs: object) -> Collection: ...
    def page_size(self, size: int) -> Collection: ...
    def limit(self, count: int) -> list[dict]: ...
"""


# ── Paginator stub ────────────────────────────────────────────────────────────

def _generate_paginator_stub() -> str:
    return """\
# Auto-generated by scripts/generate_stubs.py — do not edit manually
from __future__ import annotations
from typing import Iterator

class PageIterator:
    def __iter__(self) -> Iterator[dict]: ...
    def build_full_result(self) -> dict: ...

class Paginator:
    def paginate(self, **kwargs: object) -> PageIterator: ...
"""


# ── Waiter stub ───────────────────────────────────────────────────────────────

def _generate_waiter_stub() -> str:
    return """\
# Auto-generated by scripts/generate_stubs.py — do not edit manually

class Waiter:
    def wait(self, **kwargs: object) -> None: ...
"""


# ── Client stub ──────────────────────────────────────────────────────────────

def _generate_client_stub(service_name: str, definition: dict) -> str:
    paginators = definition.get("paginators", {})
    waiters    = definition.get("waiters", {})

    lines = [
        "# Auto-generated by scripts/generate_stubs.py — do not edit manually",
        f"# Source: scpv2/resources/data/{service_name}.json",
        "from __future__ import annotations",
        "from typing import Literal, overload",
    ]
    if paginators:
        lines.append("from scpv2.stubs.paginator import Paginator")
    if waiters:
        lines.append("from scpv2.stubs.waiter import Waiter")
    lines += ["", f"class {_client_class_name(service_name)}:"]

    client_methods = definition.get("client_methods", {})
    for method_name, spec in client_methods.items():
        params   = spec.get("params", [])
        required = spec.get("required", [])
        ordered  = [p for p in params if p in required] + \
                   [p for p in params if p not in required]
        sigs = ["self"] + [_param_sig(p, required) for p in ordered]
        lines.append(f"    def {method_name}({', '.join(sigs)}) -> dict: ...")

    # get_paginator() overloads
    if paginators:
        for op_name in paginators:
            lines.append("    @overload")
            lines.append(f'    def get_paginator(self, operation_name: Literal["{op_name}"]) -> Paginator: ...')
        lines.append("    def get_paginator(self, operation_name: str) -> Paginator: ...")

    # get_waiter() overloads
    if waiters:
        for waiter_name in waiters:
            lines.append("    @overload")
            lines.append(f'    def get_waiter(self, waiter_name: Literal["{waiter_name}"]) -> Waiter: ...')
        lines.append("    def get_waiter(self, waiter_name: str) -> Waiter: ...")

    if not client_methods and not paginators and not waiters:
        lines.append("    ...")

    return "\n".join(lines)


# ── ServiceResource stub ─────────────────────────────────────────────────────

def _generate_resource_stub(service_name: str, definition: dict) -> str:
    collections   = definition.get("collections", {})
    resource_methods = definition.get("resource_methods", {})

    lines = [
        "# Auto-generated by scripts/generate_stubs.py — do not edit manually",
        f"# Source: scpv2/resources/data/{service_name}.json",
        "from __future__ import annotations",
    ]
    if collections:
        lines.append("from scpv2.stubs.collection import Collection")
    lines += ["", f"class {_resource_class_name(service_name)}:"]

    # 컬렉션 속성
    for col_name in collections:
        lines.append(f"    {col_name}: Collection")

    # resource 메서드
    for method_name, spec in resource_methods.items():
        params   = spec.get("params", [])
        required = spec.get("required", [])
        ordered  = [p for p in params if p in required] + \
                   [p for p in params if p not in required]
        sigs = ["self"] + [_param_sig(p, required) for p in ordered]
        lines.append(f"    def {method_name}({', '.join(sigs)}) -> dict: ...")

    if not collections and not resource_methods:
        lines.append("    ...")

    return "\n".join(lines)


# ── Session stub ─────────────────────────────────────────────────────────────

def _generate_session_stub(services: list) -> str:
    lines = [
        "# Auto-generated by scripts/generate_stubs.py — do not edit manually",
        "from __future__ import annotations",
        "from typing import Literal, overload",
        "",
    ]

    for service_name in services:
        lines.append(
            f"from scpv2.stubs.{_client_module_name(service_name)} import {_client_class_name(service_name)}"
        )
        lines.append(
            f"from scpv2.stubs.{_resource_module_name(service_name)} import {_resource_class_name(service_name)}"
        )

    lines += ["", "class Session:"]

    # client() overloads
    for service_name in services:
        lines.append("    @overload")
        lines.append(
            f'    def client(self, service_name: Literal["{service_name}"]) '
            f"-> {_client_class_name(service_name)}: ..."
        )
    lines.append("    def client(self, service_name: str) -> object: ...")

    lines.append("")

    # resource() overloads
    for service_name in services:
        lines.append("    @overload")
        lines.append(
            f'    def resource(self, service_name: Literal["{service_name}"]) '
            f"-> {_resource_class_name(service_name)}: ..."
        )
    lines.append("    def resource(self, service_name: str) -> object: ...")

    return "\n".join(lines)


# ── main ─────────────────────────────────────────────────────────────────────

def main():
    # Collection stub 생성
    collection_stub_path = os.path.join(OUT_DIR, "collection.pyi")
    with open(collection_stub_path, "w") as f:
        f.write(_generate_collection_stub())
    print(f"생성: {collection_stub_path}")

    # Paginator stub 생성
    paginator_stub_path = os.path.join(OUT_DIR, "paginator.pyi")
    with open(paginator_stub_path, "w") as f:
        f.write(_generate_paginator_stub())
    print(f"생성: {paginator_stub_path}")

    # Waiter stub 생성
    waiter_stub_path = os.path.join(OUT_DIR, "waiter.pyi")
    with open(waiter_stub_path, "w") as f:
        f.write(_generate_waiter_stub())
    print(f"생성: {waiter_stub_path}")

    services = []

    for filename in sorted(os.listdir(DATA_DIR)):
        if not filename.endswith(".json"):
            continue

        filepath = os.path.join(DATA_DIR, filename)
        with open(filepath) as f:
            definition = json.load(f)

        service_name = definition["service_name"]

        # Client stub
        client_stub = _generate_client_stub(service_name, definition)
        client_path = os.path.join(OUT_DIR, f"{_client_module_name(service_name)}.pyi")
        with open(client_path, "w") as f:
            f.write(client_stub + "\n")
        print(f"생성: {client_path}")

        # Resource stub
        resource_stub = _generate_resource_stub(service_name, definition)
        resource_path = os.path.join(OUT_DIR, f"{_resource_module_name(service_name)}.pyi")
        with open(resource_path, "w") as f:
            f.write(resource_stub + "\n")
        print(f"생성: {resource_path}")

        services.append(service_name)

    # Session stub
    session_stub = _generate_session_stub(services)
    session_stub_path = os.path.join(SESSION_STUB_DIR, "session.pyi")
    with open(session_stub_path, "w") as f:
        f.write(session_stub + "\n")
    print(f"생성: {session_stub_path}")
    print(f"\n총 {len(services)}개 서비스 stub 생성 완료: {', '.join(services)}")


if __name__ == "__main__":
    main()
