#!/usr/bin/env python3
"""
scripts/generate_stubs.py
scpv2/resources/data/*.json 을 읽어서 scpv2/stubs/ 디렉토리에 .pyi stub 파일을 자동 생성합니다.

사용법:
    python scripts/generate_stubs.py

생성 결과:
    scpv2/stubs/{service}_client.pyi  : 서비스별 Client 클래스 타입 정의
    scpv2/stubs/session.pyi           : Session.client() overload 타입 정의
"""

import json
import os

DATA_DIR          = os.path.join("scpv2", "resources", "data")
OUT_DIR           = os.path.join("scpv2", "stubs")   # 서비스별 Client 스텁
SESSION_STUB_DIR  = "scpv2"                           # session.pyi — .py 파일 옆에 위치해야 Pylance가 인식

# 파라미터 이름으로 Python 타입 추론
PARAM_TYPE_MAP = {
    "size":  "int",
    "page":  "int",
    "count": "int",
    "tags":  "list",
}


def _py_type(param_name: str) -> str:
    return PARAM_TYPE_MAP.get(param_name, "str")


def _param_sig(name: str, required: list) -> str:
    t = _py_type(name)
    if name in required:
        return f"{name}: {t}"
    return f"{name}: {t} | None = None"


def _class_name(service_name: str) -> str:
    return f"{service_name.capitalize()}Client"


def _module_name(service_name: str) -> str:
    return f"{service_name}_client"


def _generate_client_stub(service_name: str, definition: dict) -> str:
    lines = [
        "# Auto-generated by scripts/generate_stubs.py — do not edit manually",
        f"# Source: scpv2/resources/data/{service_name}.json",
        "# Output: scpv2/stubs/",
        "",
        f"class {_class_name(service_name)}:",
    ]

    client_methods = definition.get("client_methods", {})
    if not client_methods:
        lines.append("    ...")
        return "\n".join(lines)

    for method_name, spec in client_methods.items():
        params   = spec.get("params", [])
        required = spec.get("required", [])

        # required 파라미터 먼저, optional 나중 (Python 문법 규칙)
        ordered = [p for p in params if p in required] + \
                  [p for p in params if p not in required]

        sigs = ["self"] + [_param_sig(p, required) for p in ordered]
        lines.append(f"    def {method_name}({', '.join(sigs)}) -> dict: ...")

    return "\n".join(lines)


def _generate_session_stub(services: list) -> str:
    lines = [
        "# Auto-generated by scripts/generate_stubs.py — do not edit manually",
        "from __future__ import annotations",
        "from typing import Literal, overload",
        "",
    ]

    for service_name in services:
        lines.append(
            f"from scpv2.stubs.{_module_name(service_name)} import {_class_name(service_name)}"
        )

    lines += ["", "class Session:"]

    for service_name in services:
        lines.append(f'    @overload')
        lines.append(
            f'    def client(self, service_name: Literal["{service_name}"]) '
            f'-> {_class_name(service_name)}: ...'
        )

    lines.append('    def client(self, service_name: str) -> object: ...')

    return "\n".join(lines)


def main():
    services = []

    for filename in sorted(os.listdir(DATA_DIR)):
        if not filename.endswith(".json"):
            continue

        filepath = os.path.join(DATA_DIR, filename)
        with open(filepath) as f:
            definition = json.load(f)

        service_name = definition["service_name"]

        stub_content  = _generate_client_stub(service_name, definition)
        stub_filename = os.path.join(OUT_DIR, f"{_module_name(service_name)}.pyi")

        with open(stub_filename, "w") as f:
            f.write(stub_content + "\n")

        print(f"생성: {stub_filename}")
        services.append(service_name)

    session_stub = _generate_session_stub(services)
    session_stub_path = os.path.join(SESSION_STUB_DIR, "session.pyi")
    with open(session_stub_path, "w") as f:
        f.write(session_stub + "\n")
    print(f"생성: {session_stub_path}")
    print(f"\n총 {len(services)}개 서비스 stub 생성 완료: {', '.join(services)}")


if __name__ == "__main__":
    main()
